name: Deploy to Namecheap

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install lftp
        run: sudo apt-get install lftp -y

      - name: Upload via FTP (DEBUG MODE)
        run: |
          lftp -d -e "
          set ftp:ssl-allow no;
          set ftp:passive-mode on;
          open -u ${{ secrets.SFTP_USER }},${{ secrets.SFTP_PASS }} sftp://${{ secrets.SFTP_HOST }}:${{ secrets.SFTP_PORT }};
          ls;
          bye
          "
