name: Update Sitemap

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: node build-sitemap.js
        env:
          YT_KEY: ${{ secrets.YT_KEY }}

      - run: |
          git config user.name "bot"
          git config user.email "bot@github.com"
          git add sitemap.xml
          git commit -m "auto sitemap update"
          git push
